package:
  name: esgf-pyclient
  version: "0.1.6"

source:
  fn: esgf-pyclient-0.1.6.tar.gz
  url: https://files.pythonhosted.org/packages/2b/9d/16ffd2c1b2d30ee350e55a23168395659366903da05c413db24ee1b374e1/esgf-pyclient-0.1.6.tar.gz
  md5: 228ac9d7e3a600f587c7cb46c7389cdc
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - esgf-pyclient = esgf-pyclient:main
    #
    # Would create an entry point called esgf-pyclient that calls esgf-pyclient.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - jinja2

  run:
    - python
    - jinja2

test:
  # Python imports
  imports:
    - pyesgf
    - pyesgf.search
    - pyesgf.security

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://esgf-pyclient.readthedocs.org
  license: BSD License
  summary: 'A library interacting with ESGF services within Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
