# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

package:
  name: sphinxcontrib-httpdomain
  version: "1.5.0"

source:
  fn: sphinxcontrib-httpdomain-1.5.0.tar.gz
  url: https://files.pythonhosted.org/packages/a5/52/0ded71896b9d25621b44d681cdd352c37a9ed81219a6b62014bd15dd2b9e/sphinxcontrib-httpdomain-1.5.0.tar.gz
  md5: db069391a08c0f0bd6aa6819f5018337
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sphinxcontrib-httpdomain = sphinxcontrib-httpdomain:main
    #
    # Would create an entry point called sphinxcontrib-httpdomain that calls sphinxcontrib-httpdomain.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - sphinx >=1.0
    - six

  run:
    - python
    - sphinx >=1.0
    - six

test:
  # Python imports
  imports:
    - sphinxcontrib
    - sphinxcontrib.autohttp

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://bitbucket.org/birkenfeld/sphinx-contrib/src/default/httpdomain/
  license: BSD License
  summary: 'Sphinx domain for HTTP APIs'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
