package:
  name: pydap
  version: "3.1.1"

source:
  fn: Pydap-3.1.1.tar.gz
  url: https://files.pythonhosted.org/packages/cd/da/577a2b6721e9b103f1671bd020f5553e582f2c509fe5cade636822b35351/Pydap-3.1.1.tar.gz
  md5: d13630328c121eeeb0e0f015eb9e7124
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pydap = pydap:main
    #
    # Would create an entry point called pydap that calls pydap.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - paste
    - paste.deploy

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - nose >=0.11
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pythonpaste.org/deploy/
  license: MIT License
  summary: 'Load, configure, and compose WSGI applications and servers'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
