package:
  name: ocw
  version: 1.1.0

source:
  git_url: https://github.com/apache/climate.git
  # git_rev: 1.1.0

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - basemap
    - netcdf4
    - h5py
    - bottle
    - pydap
    - python-dateutil
    - mock
    - myproxyclient
    - webtest
    - esgf-pyclient

test:
  # Python imports
  imports:
    - ocw
    - ocw.data_source
    - ocw.esgf

about:
  home: http://climate.apache.org/
  license: Apache License
  summary: 'A library for simplifying the process of climate model evaluation.'
